<?php

/**
 * @file
 * Use this module to learn about Drupal's menu system.
 */

/**
 * Implements hook_menu().
 */
function menufun_menu() {
  $items['menufun'] = array(
    'title' => 'Greeting',
    'title callback' => 'menufun_title',
    'description' => 'A salutation',
    // 'access callback' => TRUE,
    'access arguments' => array('receive greeting'),
    'page callback' => 'menufun_greeting_hello',
    'page arguments' => array('Jane', 'Dow'),
    'file' => 'menufun_greeting.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -1,
  );

  $items['menufun/farewell'] = array(
    'title' => 'Farewell',
    // 'access callback' => TRUE,
    'access arguments' => array('receive greeting'),
    'page callback' => 'menufun_farewell',
    'file' => 'menufun_greeting.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  // A wildcard at the end of the menu path does not interfere with the
  // passing of additional parts of the URL to the page callback, because
  // the wildcard matches only up to the next slash.
  // Experiment with various paths, for example:
  // menufun/john/dow/james/den -> Greeting...
  // menufun/john/hi/dow/james/den ->  Hello...
  $items['menufun/%/hi'] = array(
    'title' => 'Hi',
    'access callback' => TRUE,
    'page callback' => 'menufun_hello',
    'page arguments' => array(1),
  );

  // Try this: /menufun/param/foo/bar
  $items['menufun/param/%menufun_param/%'] = array(
    'title' => 'Parameters',
    'access callback' => TRUE,
    'page callback' => 'menufun_param',
    'page arguments' => array(2),
    'load arguments' => array(3),
  );

  return $items;
}


/**
 * Page callback.
 */
function menufun_hello($first_name = '', $last_name = '', $from_first_name = '', $from_last_name = '') {
  // If a page callback function uses an argument list array, and its path is
  // requested with optional path arguments, then the list array's arguments
  // are passed to the callback function first, followed by the optional path
  // arguments.
  $substitute = array(
    '@fn' => $first_name,
    '@ln' => $last_name,
    '@ffn' => $from_first_name,
    '@fln' => $from_last_name,
  );

  return t('Hello @fn @ln from @ffn @fln', $substitute);
}

/**
 * Title callback.
 */
function menufun_title() {
  // The title is shown as menu item title and a title of the page.
  // To decouple the titles drupal_set_title is used.
  drupal_set_title(t('The page title'));
  $now = format_date(time());
  return t('It is now @time', array('@time' => $now));
}

/**
 * Param page callback.
 */
function menufun_param($param1 = '', $param2 = '') {
  return t("params: @p1, @p2", array('@p1' => $param1, '@p2' => $param2));
}

/**
 * Wildcard autoloader function.
 */
function menufun_param_load($wildcard, $param = '') {
  dpm($param);
  return 'replace_' . $wildcard . ', replace_' . $param;
}

/**
 * Implements hook_permission().
 */
function menufun_permission() {
  $permissions['receive greeting'] = array(
    'title' => t('Receive a greeting'),
    'description' => t('Allow users receive a greeting message'),
  );

  return $permissions;
}
