<?php

/**
 * @file
 * Use this module to learn about Drupal's menu system.
 */

/**
 * Implements hook_menu().
 */
function menufun_menu() {
  $items['menufun'] = array(
    'title' => 'Greeting',
    'title callback' => 'menufun_title',
    'description' => 'A salutation',
    // 'access callback' => TRUE,
    'access arguments' => array('receive greeting'),
    'page callback' => 'menufun_greeting_hello',
    'page arguments' => array('Jane', 'Dow'),
    'file' => 'menufun_greeting.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -1,
  );

  $items['menufun/farewell'] = array(
    'title' => 'Farewell',
    // 'access callback' => TRUE,
    'access arguments' => array('receive greeting'),
    'page callback' => 'menufun_farewell',
    'file' => 'menufun_greeting.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  // A wildcard at the end of the menu path does not interfere with the
  // passing of additional parts of the URL to the page callback, because
  // the wildcard matches only up to the next slash.
  // Experiment with various paths, for example:
  // menufun/john/dow/james/den -> Greeting...
  // menufun/john/hi/dow/james/den ->  Hello...
  $items['menufun/%/hi'] = array(
    'title' => 'Hi',
    'access callback' => TRUE,
    'page callback' => 'menufun_hello',
    'page arguments' => array(1),
  );

  // Try this: /menufun/param/foo/bar
  $items['menufun/param/%menufun_param/%'] = array(
    'title' => 'Parameters',
    'access callback' => TRUE,
    'page callback' => 'menufun_param',
    'page arguments' => array(2),
    'load arguments' => array(3),
  );

  $items['menufun/uid/%menufun_uid'] = array(
    'title' => 'User Id',
    'access callback' => TRUE,
    'page callback' => 'menufun_uid',
    'page arguments' => array(2),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Page callback.
 */
function menufun_hello($first_name = '', $last_name = '', $from_first_name = '', $from_last_name = '') {
  // If a page callback function uses an argument list array, and its path is
  // requested with optional path arguments, then the list array's arguments
  // are passed to the callback function first, followed by the optional path
  // arguments.
  $substitute = array(
    '@fn' => $first_name,
    '@ln' => $last_name,
    '@ffn' => $from_first_name,
    '@fln' => $from_last_name,
  );

  return t('Hello @fn @ln from @ffn @fln', $substitute);
}

/**
 * Title callback.
 */
function menufun_title() {
  // The title is shown as menu item title and a title of the page.
  // To decouple the titles drupal_set_title is used.
  drupal_set_title(t('The page title'));
  $now = format_date(time());
  return t('It is now @time', array('@time' => $now));
}

/**
 * Param page callback.
 */
function menufun_param($param1 = '', $param2 = '') {
  return t("params: @p1, @p2", array('@p1' => $param1, '@p2' => $param2));
}

/**
 * Wildcard autoloader function.
 */
function menufun_param_load($wildcard, $param = '') {
  // dpm($param);
  return 'replace_' . $wildcard . ', replace_' . $param;
}

/**
 * Uid page callback.
 */
function menufun_uid($uid) {
  return t("Uid: @uid", array('@uid' => $uid));
}

/**
 * Demonstrates _to_arg() function.
 */
function menufun_uid_to_arg($uid) {
  // dpm($uid);
  if ($uid == '%') {
    global $user;
    return $user->uid;
  }

  return $uid;
}

/**
 * Demonstrates _load() function for uid
 */

/*
function menufun_uid_load($uid) {
  if ($uid == '%') {
    global $user;
    return $user->uid;
  }

  return $uid;
}
*/

/**
 * Implements hook_permission().
 */
function menufun_permission() {
  $permissions['receive greeting'] = array(
    'title' => t('Receive a greeting'),
    'description' => t('Allow users receive a greeting message'),
  );

  return $permissions;
}


/**
 * Implements hook_menu_alter().
 */
function menufun_menu_alter(&$items) {
  // dpm($items['user/logout']);

  // Replace the page callback to 'user_logout' with a call to
  // our own page callback.
  $items['user/logout']['page callback'] = 'menufun_user_logout_cb';

  // Drupal no longer has to load the user.pages.inc file
  // since it will be calling our menufun_user_logout(), which
  // is in our module and that's already in scope.
  unset($items['user/logout']['file']);

  // dpm($items['user/logout']);
}


/**
 * Menu 'Log out' callback.
 *
 * Logs the current user out, and redirects to drupal.org.
 * This is a modified version of user_logout().
 *
 * Warning: this is not the implementation of hook_user_logout().
 * user_logout() provides a hook_user_logout(), so menufun_user_logout()
 * is treated like hook and will be called by user_logout() if menu is not
 * rebuilt to include menufun_menu_alter(). As it replaces user_logout()
 * it shall call other modules hooks of hook_user_logout. In this case
 * menufun_user_logout will be called in recurence => the name must
 * be changed to avoid collision with hook_user_logout()
 */
function menufun_user_logout_cb() {
  global $user;

  watchdog('menufun', 'Session closed for %name.', array('%name' => $user->name));

  // Run the 'logout' operation of the user hook so modules can respond
  // to the logout if they want to.
  module_invoke_all('user_logout', $user);

  // Destroy the current session, and reset $user to the anonymous user.
  session_destroy();

  // Load the anonymous user so the global $user object will be correct
  // on any hook_exit() implementations.
  // session_destroy() calls _drupal_session_destroy(), and this function
  // calls $user = drupal_anonymous_user(), so it is not needed to use the
  // statement directly here, like in the example in PDD book.
  // $user = drupal_anonymous_user();

  drupal_goto('http://drupal.org/');
}

/**
 * Implements hook_menu_link_alter().
 */
function menufun_menu_link_alter(&$item) {
  if ($item['link_path'] == 'user/logout') {
    // dpm($item);
    $item['link_title'] = 'Sign off';
    // dpm($item);
  }
}
