<?php

/**
 * @file
 * Use this module to learn about Drupal's menu system.
 */

/**
 * Implements hook_menu().
 */
function menufun_menu() {
  $items['menufun'] = array(
    'title' => 'Greeting',
    'access callback' => TRUE,
    'page callback' => 'menufun_hello',
    'page arguments' => array('Jane', 'Dow'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Page callback.
 */
function menufun_hello($first_name = '', $last_name = '', $from_first_name = '', $from_last_name = '') {
  // If a page callback function uses an argument list array, and its path is
  // requested with optional path arguments, then the list array's arguments
  // are passed to the callback function first, followed by the optional path
  // arguments.
  $substitute = array(
    '@fn' => $first_name,
    '@ln' => $last_name,
    '@ffn' => $from_first_name,
    '@fln' => $from_last_name,
  );

  return t('Hello @fn @ln from @ffn @fln', $substitute);
}
