<?php

/**
 * @file
 * Use this module to learn about Drupal's menu system,
 * specifically how local tasks work.
 */

/**
 * Implements hook_menu().
 */
function milkshake_menu() {
  $items['milkshake'] = array(
    'title' => 'Milkshake flavors',
    'access callback' => TRUE,
    'page callback' => 'milkshake_overview',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['milkshake/list'] = array(
    'title' => 'List flavors',
    'access callback' => TRUE,
    'page callback' => 'milkshake_list',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  $items['milkshake/add'] = array(
    'title' => 'Add flavors',
    'access callback' => TRUE,
    'page callback' => 'milkshake_add',
    'type' => MENU_LOCAL_TASK,
  );

  $items['milkshake/list/fruity'] = array(
    'title' => 'Fruity flavors',
    'access callback' => TRUE,
    'page callback' => 'milkshake_list',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
  );

  $items['milkshake/list/candy'] = array(
    'title' => 'Candy flavors',
    'access callback' => TRUE,
    'page callback' => 'milkshake_list',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Milkshake main page callback.
 */
function milkshake_overview() {
  $output = t('The following flavors are available...');

  return $output;
}

/**
 * Milkshake list page callback.
 */
function milkshake_list($type = '') {
  $output = t('List @type flavors', array('@type' => $type));

  return $output;
}

/**
 * Milkshake add page callback.
 */
function milkshake_add() {
  $output = t('A handy form to add flavors might go here...');

  return $output;
}
