<?php

/**
 * @file
 * Use this module to learn about Drupal's menu system,
 * specifically how local tasks work.
 */

/**
 * Implements hook_menu().
 */
function milkshake_menu() {
  $items['milkshake'] = array(
    'title' => 'Milkshake flavors',
    'access callback' => TRUE,
    'page callback' => 'milkshake_overview',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['milkshake/list'] = array(
    'title' => 'List flavors',
    'access callback' => TRUE,
    'page callback' => 'milkshake_list',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['milkshake/add'] = array(
    'title' => 'Add flavors',
    'access callback' => TRUE,
    'page callback' => 'milkshake_add',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Milkshake main page callback.
 */
function milkshake_overview() {
  $output = t('The following flavors are available...');

  return $output;
}

/**
 * Milkshake list page callback.
 */
function milkshake_list() {
  $output = t('Milkshake list');

  return $output;
}
