<?php

/**
 * @file
 * Install file for RGB Color module.
 */

/**
 * Implements hook_field_schema().
 */
function rgb_color_field_schema($field) {
  _rgb_color_trace(__FUNCTION__);
  dpm($field);

  return array(
    'columns' => array(
      'rgb' => array(
        'type' => 'varchar',
        'length' => 7,
        'not null' => FALSE,
      ),
    ),
    'indexes' => array(
      'rgb' => array('rgb'),
    ),
  );
}

function _rgb_color_trace($mark) {
  dpm($mark);
}
