<?php

/**
 * @file
 * Implements various blocks to improve pending content workflow.
 */


/**
 * Implements hook_block_info().
 *
 * The hook is called on block config page (admin/structure/block). Then the
 * defined blocks appear in the list of blocks on the block administration
 * page, but 'status', 'region' parametes seems not to work and the block
 * cannot be enabled.
 *
 * The hook is called also on module activation, and only then 'status',
 * 'region' parameters are processed and the block can be activated. In other
 * words, the hook shall be ready before the module is enabled.
 */
function approval_block_info() {
  _approval_trace(__FUNCTION__);

  $blocks['pending_comments'] = array(
    'info' => t('Pending comments'),
    // Enable the block by defaul for Sidebar first region.
    'status' => 1,
    'region' => 'sidebar_first',
    'weight' => 0,
    // 'visibility' => 1,
  );

  return $blocks;
}


/**
 * Implements hook_block_configure().
 *
 * The hook is called on accessing the block configuration page.
 */
function approval_block_configure($delta = '') {
  _approval_trace(__FUNCTION__);
  // dpm($delta);

  $form = array();
  switch ($delta) {
    case 'pending_comments':
      $form['approval_pending_comments'] = array(
        '#type' => 'textfield',
        '#title' => t('Number of displayed comments'),
        '#description' => t('Enter the number of pending comments that will appear in the block.'),
        '#size' => 6,
        '#default_value' => variable_get('approval_pending_comments', 5),
      );
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function approval_block_save($delta = '', $edit = array()) {
  _approval_trace(__FUNCTION__);
  // dpm($delta);
  // dpm($edit);

  switch ($delta) {
    case 'pending_comments':
      variable_set('approval_pending_comments', (int) $edit['approval_pending_comments']);
      break;
  }
}


/**
 * Traces module functions' calls.
 */
function _approval_trace($mark) {
  dpm($mark);
}
