<?php

/**
 * @file
 * Keeps track of user logins.
 */

/**
 * Implements hook_user_login().
 */
function loginhistory_user_login(&$edit, $account) {
  // dpm($edit);
  // dpm($account);

  $id = db_insert('login_history')->fields(array(
    'uid' => $account->uid,
    'login' => $account->login,
  ))->execute();
}


/**
 * Implements hook_user_view().
 */
function loginhistory_user_view($account, $view_mode, $langcode) {
  // dpm($account);

  $limit = 10;
  // $result = db_query("SELECT login FROM {login_history}
  // WHERE uid = :uid LIMIT :limit",
  // array(':uid' => $account->uid, ':limit' => '10'));
  $result = db_select('login_history', 'lh')
    ->fields('lh', array('login'))
    ->condition('lh.uid', $account->uid)
    ->range(0, $limit)
    ->orderBy('login', 'DESC')
    ->execute();

  $output = '';
  foreach ($result as $row) {
    $output .= date("Y-m-d H:i:s", $row->login) . '<br/>';
  }

  $account->content['login'] = array(
    '#type' => 'user_profile_category',
    '#title' => t("Login History"),
  );

  $account->content['login']['history'] = array(
    '#type' => 'user_profile_item',
    '#title' => t("@limit latest logins", array('@limit' => $limit)),
    '#markup' => $output,
  );
}
