<?php

/**
 * @file
 * An example of how to use the new #states Form API element, allowing
 * dynamic form behavior with very simple setup.
 */


/**
 * Implements hook_menu().
 */
function formd_menu() {
  _formd_trace(__FUNCTION__);

  $items = array();

  $items['dynamic_form'] = array(
    'title' => 'Dynamic Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formd_example'),
    'access callback' => TRUE,
  );

  return $items;
}


/**
 * Creates a dynamic form.
 */
function formd_example($form, &$form_state) {
  _formd_trace(__FUNCTION__);
  // dpm($form);
  // dpm($form_state);

  $form['room_types'] = array(
    '#type' => 'radios',
    '#title' => t('What type of room do you require?'),
    '#options' => drupal_map_assoc(
      array(
        t('Study Room'),
        t('Small Conference Room'),
        t('Board Room'),
      )
    ),
  );

  $form['study_room'] = array(
    '#type' => 'fieldset',
    '#title' => t('Study Room Details'),
    '#states' => array(
      'visible' => array(
        ':input[name="room_types"]' => array('value' => t('Study Room')),
      ),
    ),
  );

  $form['study_room']['equipment'] = array(
    '#type' => 'checkboxes',
    '#title' => t('What equipment do you need?'),
    '#options' => drupal_map_assoc(
      array(
        t('Chairs'),
        t('PC'),
      )
    ),
  );

  $form['study_room']['chairs'] = array(
    '#type' => 'textfield',
    '#title' => t('How many chairs do you need?'),
    '#size' => 4,
    '#states' => array(
      'visible' => array(
        ':input[name="equipment[Chairs]"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['study_room']['pc'] = array(
    '#type' => 'textfield',
    '#title' => t('What type of PC do you need?'),
    '#size' => 15,
    '#states' => array(
      'visible' => array(
        ':input[name="equipment[PC]"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['small_conf_room'] = array(
    '#type' => 'fieldset',
    '#title' => t('Small Conference Room Details'),
    '#states' => array(
      'visible' => array(
        ':input[name="room_types"]' => array('value' => t('Small Conference Room')),
      ),
    ),
  );

  $form['small_conf_room']['how_many_pcs'] = array(
    '#type' => 'select',
    '#title' => t('How many PCs do you need set up in the small conference room?'),
    '#options' => array(
      1 => t('One'),
      2 => t('Two'),
      3 => t('Three'),
      4 => t('Four'),
      5 => t('Lots'),
    ),
  );

  $form['small_conf_room']['comment'] = array(
    '#type' => 'item',
    '#description' => t("Wow, that's a long time."),
    '#states' => array(
      'visible' => array(
        ':input[name="how_many_pcs"]' => array('value' => '5'),
      ),
    ),
  );

  $form['small_conf_room']['room_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Which room do you want to use?'),
  );

  $form['small_conf_room']['hours'] = array(
    '#type' => 'select',
    '#title' => t('Do you want to reserve the room when it is free
      (no fees) or paid (prime time)?'),
    '#options' => drupal_map_assoc(array(t('Free'), t('Paid'))),
  );

  $form['small_conf_room']['hours_writein'] = array(
    '#type' => 'textfield',
    '#title' => t('Please enter the date and time you would like to
      reserve the room and the duration.'),
    '#size' => 50,
    '#states' => array(
      'visible' => array(
        // All conditions must be met, so one is commented out.
        ':input[name="hours"]' => array('value' => t('Free')),
        // ':input[name="hours"]' => array('value' => t('Paid')),
      ),
    ),
  );

  $form['small_conf_room']['remainder'] = array(
    '#type' => 'item',
    '#description' => t('Remember to enter the date, start time, and end time.'),
    '#states' => array(
      'visible' => array(
        'input[name="hours_writein"]' => array('filled' => FALSE),
      ),
    ),
  );

  $form['board_room'] = array(
    '#type' => 'fieldset',
    '#title' => t('Board Room Details'),
    '#states' => array(
      'visible' => array(
        'input[name="room_types"]' => array('value' => t('Board Room')),
      ),
    ),
  );

  $form['board_room']['more_info'] = array(
    '#type' => 'textarea',
    '#title' => t('Please enter the date and time of when you would
      like to reserve the board room.'),
  );

  $form['board_room']['info_provide'] = array(
    '#type' => 'checkbox',
    '#title' => t('Check here if you have provided information above'),
    '#disabled' => TRUE,
    '#states' => array(
      'checked' => array(
        ':input[name="more_info"]' => array('filled' => TRUE),
      ),
    ),
  );

  $form['expand_more_info'] = array(
    '#type' => 'checkbox',
    '#title' => t('Check here if you want to add special instructions.'),
  );

  $form['more_info'] = array(
    '#type' => 'fieldset',
    '#title' => t('Special Instructions'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#states' => array(
      'expanded' => array(
        'input[name="expand_more_info"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['more_info']['feedback'] = array(
    '#type' => 'textarea',
    '#title' => t('Please provide any additional details that will
      help us better serve you.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}


/**
 * Form submission handler.
 */
function formd_example_submit($form, &$form_state) {
  _formd_trace(__FUNCTION__);
  drupal_set_message(t('Submitting values: @values',
    array('@values' => var_export($form_state['values'], TRUE))));
}


/**
 * Traces module's functions calls.
 */
function _formd_trace($mark) {
  dpm($mark);
}
