<?php

/**
 * @file
 * Demonstrates users related topics.
 */

/**
 * Implements hook_menu().
 */
function users_menu() {
  $items['users'] = array(
    'title' => 'Users',
    'access callback' => TRUE,
    'page callback' => 'users_sandbox',
  );

  return $items;
}

/**
 * Handles user examples.
 */
function users_sandbox() {
  global $user;

  dpm($user);

  $output = user_is_logged_in() ? 'User is logged in.' : 'User is an anonymous user.';

  return t('@o', array('@o' => $output));
}


/**
 * Implements hook_user_view().
 */
function users_user_view($account, $view_mode, $langcode) {
  dpm($account);
  unset($account->content['summary']);

  $account->content['details'] = array(
    '#type' => 'user_profile_category',
    '#title' => t('Details'),
    //'#attributes' => array('class' => array('user-member')),
    '#weight' => 0,
    );

  $account->content['details']['member'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Member'),
    '#markup' => t('This user is the member of this portal.'),
  );

  $account->content['details']['data'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Personal data'),
    '#markup' => t('Personal data of the user.'),
  );

  dpm($account);
}
