<?php

/**
 * @file
 * A module that emails a person when taxonomy changes.
 */

include_once DRUPAL_ROOT . '/sites/all/modules/pdd/include/tools.inc';

/**
 * Implements hook_taxonomy_term_insert().
 */
function taxomon_taxonomy_term_insert($term) {
  pdd_trace_funct();
  dpm($term);
}


/**
 * Implements hook_taxonomy_term_update().
 */
function taxomon_taxonomy_term_update($term) {
  pdd_trace_funct();
  dpm($term);
}


/**
 * Implements hook_taxonomy_term_delete().
 */
function taxomon_taxonomy_term_delete($term) {
  pdd_trace_funct();
  dpm($term);
}


/**
 * Implements hook_taxonomy_vocabulary_insert().
 */
function taxomon_taxonomy_vocabulary_insert($vocabulary) {
  pdd_trace_funct();
  dpm($vocabulary);
}


/**
 * Implements hook_taxonomy_vocabulary_update().
 */
function taxomon_taxonomy_vocabulary_update($vocabulary) {
  pdd_trace_funct();
  dpm($vocabulary);
}


/**
 * Implements hook_taxonomy_vocabulary_delete().
 */
function taxomon_taxonomy_vocabulary_delete($vocabulary) {
  pdd_trace_funct();
  dpm($vocabulary);
}


/**
 * Implements hook_menu().
 */
function taxomon_menu() {
  pdd_trace_funct();

  $items = array();
  $items['nodeterm'] = array(
    'title' => 'Node terms',
    'access callback' => TRUE,
    'page callback' => 'taxomon_node_terms',
  );

  return $items;
}


/**
 * Displays taxonomy terms associated with a node
 */
function taxomon_node_terms($nid = NULL) {
  pdd_trace_funct();
  dpm($nid);
  return t('Hello');
}


/**
 * Log changes to taxonomy using watchdog and email.
 */
function _taxonom_send_notification($type, $action, $name) {
  // Send email here.
}
