<?php

/**
 * @file
 * Use this module to learn Drupal's database interface.
 */

/**
 * Implements hook_menu().
 */
function dbasebox_menu() {
  $items = array();

  $items['dbasebox'] = array(
    'title' => 'Database Box',
    'page callback' => 'dbasebox_sandbox',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['dbasebox/query'] = array(
    'title' => 'Static query',
    'page callback' => 'dbasebox_query',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 0,
  );

  $items['dbasebox/select'] = array(
    'title' => 'Dynamic query',
    'page callback' => 'dbasebox_select',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  );

  $items['dbasebox/insert'] = array(
    'title' => 'Insert',
    'page callback' => 'dbasebox_insert',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 2,
  );

  $items['dbasebox/update'] = array(
    'title' => 'Update',
    'page callback' => 'dbasebox_update',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 3,
  );

  $items['dbasebox/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'dbasebox_delete',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 4,
  );

  $items['dbasebox/sfield'] = array(
    'title' => 'Single field',
    'page callback' => 'dbasebox_sfield',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 5,
  );

  return $items;
}

/**
 * Database main page callback.
 */
function dbasebox_sandbox() {
  return t('Select database action from DbaseBox menu');
}


/**
 * Database query page callback.
 */
function dbasebox_query() {

  $output = '';

  // Simple query.
  $output .= 'SELECT nid, title FROM {node}:<br/>';
  $result = db_query('SELECT nid, title FROM {node}');

  foreach ($result as $row) {
    $output .= $row->nid . ": " . $row->title . '<br/>';
    // dpm($row);
  }

  // Simple query with placeholder.
  // SELECT name FROM role WHERE rid = 2
  $output .= '<br/>SELECT name FROM {role} WHERE rid = 2:<br/>';
  $result = db_query('SELECT name FROM {role} WHERE rid = :rid',
    array(':rid' => 2));

  foreach ($result as $row) {
    $output .= $row->name . '<br/>';
    // dpm($row);
  }

  // Simple query with placeholders.
  $output .= '<br/>SELECT name FROM {role} WHERE rid > 0 AND rid < 3:<br/>';
  $result = db_query('SELECT name FROM {role} WHERE rid > :min_rid AND rid < :max_rid',
    array(':min_rid' => 0, ':max_rid' => 3));

  foreach ($result as $row) {
    $output .= $row->name . '<br/>';
  }

  // Simple query with variable placeholder.
  $output .= '<br/>SELECT * FROM {dbasebox} WHERE bid = 2:<br/>';
  $bunny = array('bid' => 2);
  $result = db_query('SELECT * FROM {dbasebox} WHERE bid = :bid',
    array(':bid' => $bunny['bid']));

  foreach ($result as $row) {
    $output .= $row->bid . ': ' . $row->name . ' - ' . $row->tons . '<br/>';
  }

  return $output;
}

/**
 * Dynamic query page callback
 */
function dbasebox_select() {
  $output = '';

  // Simple query.
  $output .= 'SELECT nid, title FROM {node}:<br/>';
  $result = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->execute();

  foreach ($result as $row) {
    $output .= $row->nid . ": " . $row->title . '<br/>';
  }

  // Simple query with placeholder.
  $output .= '<br/>SELECT name FROM {role} WHERE rid = 2:<br/>';
  $result = db_select('role', 'r')
  ->fields('r', array('name'))
  ->condition('rid', 2)
  ->execute();

  foreach ($result as $row) {
    $output .= $row->name . '<br/>';
  }

  // Simple query with placeholders.
  $output .= '<br/>SELECT name FROM {role} WHERE rid > 0 AND rid < 3:<br/>';
  $result = db_select('role', 'r')
    ->fields('r', array('name'))
    ->condition('rid', 0, '>')
    ->condition('rid', 3, '<')
    ->execute();

  foreach ($result as $row) {
    $output .= $row->name . '<br/>';
  }

  // Simple query with variable placeholder.
  $output .= '<br/>SELECT * FROM {dbasebox} WHERE bid = 2:<br/>';
  $bunny = array('bid' => 2);
  $result = db_select('dbasebox', 'd')
    ->fields('d')
    ->condition('bid', 2)
    ->execute();

  foreach ($result as $row) {
    $output .= $row->bid . ': ' . $row->name . ' - ' . $row->tons . '<br/>';
  }

  return $output;
}


/**
 * Database insert page callback.
 */
function dbasebox_insert() {
  // Multi insert form.
  $bid = db_insert('dbasebox')
  ->fields(array('name', 'tons'))
  ->values(array('Melman', 6))
  ->values(array('Vitaly', 3))
  ->values(array('Kowalsky', 7))
  ->execute();

  return dbasebox_print();
}


/**
 * Database update page callback.
 */
function dbasebox_update() {
  $updated_num = db_update('dbasebox')
  ->fields(array(
    'tons' => 0,
  ))
  ->condition('bid', 3, '>=')
  ->execute();

  $output = "Updated $updated_num entries.<br/><br/>";

  $output .= dbasebox_print();

  return $output;
}

/**
 * Database delete page callback.
 */
function dbasebox_delete() {
  $deleted_num = db_delete('dbasebox')
    ->condition('tons', 0)
    ->execute();

  $output = "Deleted $deleted_num entries.<br/><br/>";

  $output .= dbasebox_print();

  return $output;
}

/**
 * Database single value page callback.
 */
function dbasebox_sfield() {
  $sfield = db_query("SELECT * FROM {dbasebox}")->fetchField(1);

  return $sfield;
}

/**
 * Prints dbasebox database content.
 */
function dbasebox_print() {
  $output = 'SELECT * FROM {dbasebox}:<br/>';
  $result = db_query('SELECT * FROM {dbasebox}');
  foreach ($result as $row) {
    $output .= $row->bid . ': ' . $row->name . ' - ' . $row->tons . '<br/>';
  }

  return $output;
}
