<?php

/**
 * @file
 * Use this module to learn Drupal's database interface.
 */

/**
 * Implements hook_menu().
 */
function dbasebox_menu() {
  $items = array();

  $items['dbasebox'] = array(
    'title' => 'Database Box',
    'page callback' => 'dbasebox_sandbox',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Database page callback.
 */
function dbasebox_sandbox() {

  $db_result = db_query("SELECT nid, title FROM {node} WHERE type = :type",
    array(':type' => 'page',));

  dpm($db_result);

  foreach($db_result as $row) {
    dpm($row);
  }

  return t('db_query done');
}

